name: Testing

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up g++
      run: | 
        sudo apt install -y g++-10
        pip uninstall conan -y
        pip install -U conan==1.59.0

    - name: Build Tests
      run: |
        mkdir build
        cd build
        conan install .. --build=missing -s build_type=Release -s compiler.libcxx=libstdc++11
        cmake ..
        cmake --build . -j4
        ctest 
